#!/bin/bash

# Presenting a GDM theme for Fedora and other platforms using the Plymouth
# splash screen manager.  It supports password and interactive prompts,
# progress throbber, boot messages and nice fadein / out when appropriate.
#
# This theme requires the script plugin for Plymouth.  Most distributions
# come with this plugin already, or have it available on their repositories.
#
# Deploy into /usr/share/plymouth/themes as a folder named Rudd-O-Embossed,
# then set it as default with:
#
#     plymouth-set-default-theme Rudd-O-Embossed -R
#
# For the full effect:
# 
# a) drop the file 10-rudd-o-embossed-settings into:
#
#       /etc/dconf/db/gdm.d
#
#    and then run the command dconf update as root
#
# b) set wallpaper.png to be your desktop's wallpaper
# 
# Alternatively, you can run this command in your shell (it will require
# sudo privileges) and it will install the plymouth theme for you.
#
# The following are executable installation instructions.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo Checking that you have the script plugin for Plymouth
for a in /usr/*/plymouth*/script.so ; do
	test -e "$a" || {
		echo You do not have the script plugin for Plymouth
		echo Use your package manager to install it and then retry this
		exit 1
	}
done

set -e

echo Installing theme to Plymouth themes directory
sudo rm -rf /usr/share/plymouth/themes/Rudd-O-Embossed/
sudo cp -R "$DIR" /usr/share/plymouth/themes/Rudd-O-Embossed/
sudo chown root.root -R /usr/share/plymouth/themes/Rudd-O-Embossed/

echo "Setting theme as default and rebuilding initial RAM disk"
sudo plymouth-set-default-theme Rudd-O-Embossed -R

echo "Setting your GNOME wallpaper to the theme wallpaper"
dconf write /org/gnome/desktop/background/picture-uri "'file:///usr/share/plymouth/themes/Rudd-O-Embossed/wallpaper.png'"

echo Copying theme-specific GDM display manager settings to /etc
sudo cp "$DIR"/10-rudd-o-embossed-settings /etc/dconf/db/gdm.d/

echo Updating GDM display manager dconf configuration
sudo dconf update
